### ISSUE TITLE
Create deployable GraphQL server

### ISSUE THREAD

**Issue by chrisjm** [openbrewerydb/openbrewerydb-graphql#1]
## Overview

The goal is to have a repo with a "Deploy to AWS" button so that anyone can deploy a GraphQL server using their own AWS account credentials and connect to a database. We'll start with a connection to RDS (relational DB; PostgreSQL) so that we can set up and deploy an official GraphQL server.

## Tasks

- [ ] Set up development environment
- [ ] Configure DB connection
- [ ] Set up Deploy to Button (not sure what this entails, so please expand)
- [ ] Deploy official OBDB GraphQL server
